[skip-ci] Try to fix REAMDE action

diff --git a/.github/workflows/Render-README.yaml b/.github/workflows/Render-README.yaml
--- a/.github/workflows/Render-README.yaml
+++ b/.github/workflows/Render-README.yaml
@@ -1,6 +1,7 @@
+# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
   push:
-    branches: [main, development]
     paths: ['README.Rmd']
 
 name: Render-README
@@ -22,15 +23,13 @@ jobs:
 
       - uses: r-lib/actions/setup-renv@v1
 
-    # Render READEME.md using rmarkdown
-    - name: render README
-      run: Rscript -e 'rmarkdown::render("README.Rmd")'
+      - name: Render README files
+        run: Rscript -e 'rmarkdown::render("README.Rmd")'
 
-    # Commit and push files to github
-    - name: commit rendered README
-      run: |
-        git config --local user.email "actions@github.com"
-        git config --local user.name "GitHub Actions"
-        git add README.md
-        git commit -m "Re-build README.md" || echo "No changes to commit"
-        git push origin || echo "No changes to commit"
+      - name: Commit README
+        run: |
+          git config --local user.email "actions@github.com"
+          git config --local user.name "GitHub Actions"
+          git add README.md
+          git commit -m "Re-build README.md" || echo "No changes to commit"
+          git push origin || echo "No changes to commit"
